package com.mygdx.game.providers;

import com.badlogic.gdx.math.MathUtils;
import com.mygdx.game.models.Vocabulary;
import com.mygdx.game.screens.WelcomeScreen;
import com.mygdx.game.models.TranslateWord;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;

public class VocabularyProvider {
    static VocabularyProvider singleInstance = null;
    public ArrayList<Vocabulary> vocabularies;
    private Map<WelcomeScreen.LANGUAGE, String> languages;

    public static VocabularyProvider getInstance() {
        if (singleInstance == null)
            singleInstance = new VocabularyProvider();
        return singleInstance;
    }

    private void createLanguages(){
        languages.put(WelcomeScreen.LANGUAGE.en,"Anglais");
        languages.put(WelcomeScreen.LANGUAGE.es,"Espagnol");
        languages.put(WelcomeScreen.LANGUAGE.fr,"Français");
    }

    public Map<WelcomeScreen.LANGUAGE, String> getLanguages() {
        return languages;
    }

    private VocabularyProvider() {
        vocabularies = new ArrayList<>();
        languages = new HashMap<>();

        createLanguages();
        createVocabularies();
    }

    public int totalOfVocabularies() {
        return vocabularies.size();
    }

    public Vocabulary pickVocabulary(int index) {
        return vocabularies.get(index);
    }

    public Vocabulary pickRandomVocabulary() {
        Vocabulary vocabulary;
        do {
            vocabulary = vocabularies.get(MathUtils.random(0, vocabularies.size() - 1));
        } while (vocabulary.countUnusedTranslateWord() == 0);
        return vocabulary;
    }

    private void createVocabularies() {
        TranslateWord translateWord = new TranslateWord();
        Vocabulary vocabulary = new Vocabulary("L'argent");
        try {
            translateWord = new TranslateWord();
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.fr, "la banque");
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.en, "the bank");
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.es, "el Banco");
            vocabulary.addTranslateWord(translateWord);
            translateWord = new TranslateWord();
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.fr, "l''argent liquide");
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.en, "cash");
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.es, "efectivo");
            vocabulary.addTranslateWord(translateWord);
            translateWord = new TranslateWord();
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.fr, "le paiement");
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.en, "payment");
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.es, "pago");
            vocabulary.addTranslateWord(translateWord);
            translateWord = new TranslateWord();
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.fr, "un carnet de chèques");
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.en, "checkbook");
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.es, "talonario de cheques");
            vocabulary.addTranslateWord(translateWord);
            translateWord = new TranslateWord();
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.fr, "déposer de l''argent");
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.en, "to deposit money");
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.es, "depositar dinero");
            vocabulary.addTranslateWord(translateWord);
            translateWord = new TranslateWord();
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.fr, "prêter de l''argent");
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.en, "to borrow money");
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.es, "pedir dinero prestado");
            vocabulary.addTranslateWord(translateWord);
            translateWord = new TranslateWord();
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.fr, "les services financiers");
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.en, "financial services");
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.es, "servicios financieros");
            vocabulary.addTranslateWord(translateWord);
            translateWord = new TranslateWord();
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.fr, "la commission");
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.en, "commission");
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.es, "comisión");
            vocabulary.addTranslateWord(translateWord);
            translateWord = new TranslateWord();
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.fr, "un investissement");
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.en, "an investment");
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.es, "una inversión");
            vocabulary.addTranslateWord(translateWord);
            translateWord = new TranslateWord();
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.fr, "un virement");
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.en, "transfer");
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.es, "transferir");
            vocabulary.addTranslateWord(translateWord);
            translateWord = new TranslateWord();
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.fr, "la gestion de l''argent");
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.en, "money management");
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.es, "administración del dinero");
            vocabulary.addTranslateWord(translateWord);
            translateWord = new TranslateWord();
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.fr, "une transaction");
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.en, "a transaction");
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.es, "una transacción");
            vocabulary.addTranslateWord(translateWord);
            translateWord = new TranslateWord();
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.fr, "un guichet automatique");
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.en, "ATM machine");
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.es, "cajero automático");
            vocabulary.addTranslateWord(translateWord);
            translateWord = new TranslateWord();
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.fr, "attendre dans la queue");
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.en, "to wait in line");
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.es, "a esperar en línea");
            vocabulary.addTranslateWord(translateWord);
            translateWord = new TranslateWord();
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.fr, "une carte bancaire");
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.en, "banking/ATM card");
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.es, "tarjeta bancaria / ATM");
            vocabulary.addTranslateWord(translateWord);
            translateWord = new TranslateWord();
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.fr, "faire des économies");
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.en, "to save money");
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.es, "para ahorrar dinero");
            vocabulary.addTranslateWord(translateWord);
            translateWord = new TranslateWord();
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.fr, "le montant");
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.en, "sum/total amount");
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.es, "suma / monto total");
            vocabulary.addTranslateWord(translateWord);
            translateWord = new TranslateWord();
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.fr, "un compte-chèques");
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.en, "checking account");
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.es, "cuenta de cheques");
            vocabulary.addTranslateWord(translateWord);
            translateWord = new TranslateWord();
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.fr, "l''argent");
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.en, "money");
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.es, "dinero");
            vocabulary.addTranslateWord(translateWord);
            translateWord = new TranslateWord();
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.fr, "les fonds");
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.en, "funds");
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.es, "fondos");
            vocabulary.addTranslateWord(translateWord);
            translateWord = new TranslateWord();
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.fr, "un chèque");
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.en, "check");
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.es, "cheque");
            vocabulary.addTranslateWord(translateWord);
            translateWord = new TranslateWord();
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.fr, "un dépôt");
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.en, "deposit");
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.es, "depositar");
            vocabulary.addTranslateWord(translateWord);
            translateWord = new TranslateWord();
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.fr, "le crédit");
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.en, "credit");
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.es, "crédito");
            vocabulary.addTranslateWord(translateWord);
            translateWord = new TranslateWord();
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.fr, "les marchés financiers");
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.en, "financial markets");
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.es, "mercados financieros");
            vocabulary.addTranslateWord(translateWord);
            translateWord = new TranslateWord();
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.fr, "la clientèle");
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.en, "clientele");
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.es, "clientela");
            vocabulary.addTranslateWord(translateWord);
            translateWord = new TranslateWord();
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.fr, "les frais");
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.en, "fees");
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.es, "Tarifa");
            vocabulary.addTranslateWord(translateWord);
            translateWord = new TranslateWord();
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.fr, "une institution financière");
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.en, "financial institution");
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.es, "institución financiera");
            vocabulary.addTranslateWord(translateWord);
            translateWord = new TranslateWord();
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.fr, "le taux d''intérêt");
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.en, "interest rate");
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.es, "tasa de interés");
            vocabulary.addTranslateWord(translateWord);
            translateWord = new TranslateWord();
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.fr, "la monnaie");
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.en, "currency");
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.es, "moneda");
            vocabulary.addTranslateWord(translateWord);
            translateWord = new TranslateWord();
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.fr, "le bilan");
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.en, "balance");
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.es, "equilibrar");
            vocabulary.addTranslateWord(translateWord);
            translateWord = new TranslateWord();
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.fr, "prendre un numéro");
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.en, "to take a number");
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.es, "tomar un número");
            vocabulary.addTranslateWord(translateWord);
            translateWord = new TranslateWord();
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.fr, "une carte de crédit");
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.en, "credit card");
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.es, "tarjeta de crédito");
            vocabulary.addTranslateWord(translateWord);
            translateWord = new TranslateWord();
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.fr, "un emprunt");
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.en, "a loan");
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.es, "un préstamo");
            vocabulary.addTranslateWord(translateWord);
            translateWord = new TranslateWord();
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.fr, "retirer de l''argent");
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.en, "to take out money");
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.es, "sacar dinero");
            vocabulary.addTranslateWord(translateWord);
            translateWord = new TranslateWord();
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.fr, "un compte d''épargne");
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.en, "savings account");
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.es, "cuenta de ahorros");
            vocabulary.addTranslateWord(translateWord);
            translateWord = new TranslateWord();
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.fr, "un distributeur automatique");
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.en, "ATM machine");
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.es, "cajero automático");
            vocabulary.addTranslateWord(translateWord);
            translateWord = new TranslateWord();
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.fr, "un reçu");
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.en, "receipt");
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.es, "recibo");
            vocabulary.addTranslateWord(translateWord);
        } catch (Exception e) {

        }

        vocabularies.add(vocabulary);

        vocabulary = new Vocabulary("Les meubles");

        try {
            translateWord = new TranslateWord();
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.fr, "une table");
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.en, "a table");
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.es, "una mesa");
            vocabulary.addTranslateWord(translateWord);
            translateWord = new TranslateWord();
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.fr, "une chaise");
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.en, "a chair");
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.es, "una silla");
            vocabulary.addTranslateWord(translateWord);
            translateWord = new TranslateWord();
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.fr, "une bibliothèque");
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.en, "a bookcase");
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.es, "una estantería");
            vocabulary.addTranslateWord(translateWord);
            translateWord = new TranslateWord();
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.fr, "une table basse");
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.en, "a coffee table");
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.es, "una mesa para cafe");
            vocabulary.addTranslateWord(translateWord);
            translateWord = new TranslateWord();
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.fr, "une cheminée");
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.en, "a fireplace");
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.es, "una chimenea");
            vocabulary.addTranslateWord(translateWord);
            translateWord = new TranslateWord();
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.fr, "une table de chevet");
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.en, "a bedside table");
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.es, "una mesita de noche");
            vocabulary.addTranslateWord(translateWord);
            translateWord = new TranslateWord();
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.fr, "une étagère");
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.en, "a shelf");
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.es, "un estante");
            vocabulary.addTranslateWord(translateWord);
            translateWord = new TranslateWord();
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.fr, "une armoire");
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.en, "a wardrobe");
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.es, "un armario");
            vocabulary.addTranslateWord(translateWord);
            translateWord = new TranslateWord();
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.fr, "une commode");
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.en, "a dresser");
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.es, "un vestidor");
            vocabulary.addTranslateWord(translateWord);
            translateWord = new TranslateWord();
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.fr, "une moquette");
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.en, "a carpet");
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.es, "Una alfombra");
            vocabulary.addTranslateWord(translateWord);
            translateWord = new TranslateWord();
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.fr, "un siège");
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.en, "a seat");
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.es, "un asiento");
            vocabulary.addTranslateWord(translateWord);
            translateWord = new TranslateWord();
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.fr, "un tabouret");
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.en, "a stool");
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.es, "un taburete");
            vocabulary.addTranslateWord(translateWord);
            translateWord = new TranslateWord();
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.fr, "un placard");
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.en, "a cupboard");
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.es, "un armario");
            vocabulary.addTranslateWord(translateWord);
            translateWord = new TranslateWord();
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.fr, "un tiroir");
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.en, "a drawer");
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.es, "un cajon");
            vocabulary.addTranslateWord(translateWord);
            translateWord = new TranslateWord();
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.fr, "un fauteuil");
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.en, "a armchair");
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.es, "un sillón");
            vocabulary.addTranslateWord(translateWord);
            translateWord = new TranslateWord();
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.fr, "un lit");
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.en, "a bed");
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.es, "una cama");
            vocabulary.addTranslateWord(translateWord);
            translateWord = new TranslateWord();
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.fr, "un bureau");
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.en, "a desk");
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.es, "un escritorio");
            vocabulary.addTranslateWord(translateWord);
            translateWord = new TranslateWord();
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.fr, "un miroir");
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.en, "a mrror");
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.es, "un mrror");
            vocabulary.addTranslateWord(translateWord);
            translateWord = new TranslateWord();
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.fr, "un meuble");
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.en, "a piece of furniture");
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.es, "un mueble");
            vocabulary.addTranslateWord(translateWord);
            translateWord = new TranslateWord();
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.fr, "un oreiller");
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.en, "a pillow");
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.es, "una almohada");
            vocabulary.addTranslateWord(translateWord);
        } catch (Exception e) {

        }
        vocabularies.add(vocabulary);

        vocabulary = new Vocabulary("Les couleurs");

        try {
            translateWord = new TranslateWord();
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.fr, "blanc");
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.en, "white");
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.es, "blanco");
            vocabulary.addTranslateWord(translateWord);
            translateWord = new TranslateWord();
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.fr, "bleu clair");
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.en, "light blue");
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.es, "azul claro");
            vocabulary.addTranslateWord(translateWord);
            translateWord = new TranslateWord();
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.fr, "multicolore");
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.en, "muli-colored");
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.es, "multicolor");
            vocabulary.addTranslateWord(translateWord);
            translateWord = new TranslateWord();
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.fr, "gris");
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.en, "grey");
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.es, "gris");
            vocabulary.addTranslateWord(translateWord);
            translateWord = new TranslateWord();
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.fr, "vert");
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.en, "green");
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.es, "verde");
            vocabulary.addTranslateWord(translateWord);
            translateWord = new TranslateWord();
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.fr, "noir");
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.en, "black");
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.es, "negro");
            vocabulary.addTranslateWord(translateWord);
            translateWord = new TranslateWord();
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.fr, "argenté");
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.en, "silver");
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.es, "plata");
            vocabulary.addTranslateWord(translateWord);
            translateWord = new TranslateWord();
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.fr, "jaune");
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.en, "yellow");
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.es, "amarillo");
            vocabulary.addTranslateWord(translateWord);
            translateWord = new TranslateWord();
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.fr, "orange");
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.en, "orange");
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.es, "naranja");
            vocabulary.addTranslateWord(translateWord);
            translateWord = new TranslateWord();
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.fr, "bleu");
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.en, "blue");
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.es, "azul");
            vocabulary.addTranslateWord(translateWord);
            translateWord = new TranslateWord();
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.fr, "bleu foncé");
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.en, "dark blue");
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.es, "azul oscuro");
            vocabulary.addTranslateWord(translateWord);
            translateWord = new TranslateWord();
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.fr, "rose");
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.en, "pink");
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.es, "rosado");
            vocabulary.addTranslateWord(translateWord);
            translateWord = new TranslateWord();
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.fr, "rouge");
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.en, "red");
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.es, "rojo");
            vocabulary.addTranslateWord(translateWord);
            translateWord = new TranslateWord();
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.fr, "marron");
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.en, "brown");
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.es, "marrón");
            vocabulary.addTranslateWord(translateWord);
            translateWord = new TranslateWord();
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.fr, "violet");
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.en, "purple");
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.es, "púrpura");
            vocabulary.addTranslateWord(translateWord);
            translateWord = new TranslateWord();
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.fr, "beige");
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.en, "beige");
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.es, "beige");
            vocabulary.addTranslateWord(translateWord);
            translateWord = new TranslateWord();
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.fr, "turquoise");
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.en, "turquoise");
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.es, "turquesa");
            vocabulary.addTranslateWord(translateWord);
            translateWord = new TranslateWord();
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.fr, "doré");
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.en, "golden");
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.es, "dorado");
            vocabulary.addTranslateWord(translateWord);
        } catch (Exception e) {

        }
        vocabularies.add(vocabulary);

        vocabulary = new Vocabulary("La famille");

        try {
            translateWord = new TranslateWord();
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.fr, "le père");
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.en, "the father");
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.es, "el padre");
            vocabulary.addTranslateWord(translateWord);
            translateWord = new TranslateWord();
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.fr, "les parents");
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.en, "the parents");
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.es, "los padres");
            vocabulary.addTranslateWord(translateWord);
            translateWord = new TranslateWord();
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.fr, "la sœur");
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.en, "the sister");
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.es, "la hermana");
            vocabulary.addTranslateWord(translateWord);
            translateWord = new TranslateWord();
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.fr, "la fille");
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.en, "the daughter");
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.es, "la hija");
            vocabulary.addTranslateWord(translateWord);
            translateWord = new TranslateWord();
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.fr, "le bébé");
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.en, "the baby");
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.es, "el bebé");
            vocabulary.addTranslateWord(translateWord);
            translateWord = new TranslateWord();
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.fr, "la femme");
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.en, "the wife");
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.es, "La esposa");
            vocabulary.addTranslateWord(translateWord);
            translateWord = new TranslateWord();
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.fr, "la fiancée");
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.en, "the fiancée");
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.es, "la prometida");
            vocabulary.addTranslateWord(translateWord);
            translateWord = new TranslateWord();
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.fr, "la grand-mère");
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.en, "the grandmother");
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.es, "la abuela");
            vocabulary.addTranslateWord(translateWord);
            translateWord = new TranslateWord();
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.fr, "les petits-enfants");
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.en, "the grandchildren");
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.es, "los nietos");
            vocabulary.addTranslateWord(translateWord);
            translateWord = new TranslateWord();
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.fr, "la tante");
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.en, "the aunt");
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.es, "la tía");
            vocabulary.addTranslateWord(translateWord);
            translateWord = new TranslateWord();
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.fr, "la nièce");
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.en, "the niece");
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.es, "la sobrina");
            vocabulary.addTranslateWord(translateWord);
            translateWord = new TranslateWord();
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.fr, "la belle-mère");
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.en, "the step mother");
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.es, "La Madrastra");
            vocabulary.addTranslateWord(translateWord);
            translateWord = new TranslateWord();
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.fr, "la cousine");
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.en, "the cousin (female)");
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.es, "la prima (mujer)");
            vocabulary.addTranslateWord(translateWord);
            translateWord = new TranslateWord();
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.fr, "la belle-sœur");
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.en, "sister in-law");
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.es, "cuñada");
            vocabulary.addTranslateWord(translateWord);
            translateWord = new TranslateWord();
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.fr, "la mère");
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.en, "the mother");
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.es, "La madre");
            vocabulary.addTranslateWord(translateWord);
            translateWord = new TranslateWord();
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.fr, "le frère");
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.en, "the brother");
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.es, "el hermano");
            vocabulary.addTranslateWord(translateWord);
            translateWord = new TranslateWord();
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.fr, "le fils");
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.en, "the son");
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.es, "el hijo");
            vocabulary.addTranslateWord(translateWord);
            translateWord = new TranslateWord();
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.fr, "l’enfant");
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.en, "the child");
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.es, "el niño");
            vocabulary.addTranslateWord(translateWord);
            translateWord = new TranslateWord();
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.fr, "le mari");
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.en, "the husband");
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.es, "el esposo");
            vocabulary.addTranslateWord(translateWord);
            translateWord = new TranslateWord();
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.fr, "le fiancé");
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.en, "the fiancé");
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.es, "el prometido");
            vocabulary.addTranslateWord(translateWord);
            translateWord = new TranslateWord();
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.fr, "le grand-père");
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.en, "the grandfather");
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.es, "el abuelo");
            vocabulary.addTranslateWord(translateWord);
            translateWord = new TranslateWord();
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.fr, "les grand-parents");
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.en, "the grandparents");
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.es, "los abuelos");
            vocabulary.addTranslateWord(translateWord);
            translateWord = new TranslateWord();
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.fr, "l’oncle");
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.en, "the uncle");
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.es, "el tío");
            vocabulary.addTranslateWord(translateWord);
            translateWord = new TranslateWord();
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.fr, "le neveu");
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.en, "the nephew");
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.es, "el sobrino");
            vocabulary.addTranslateWord(translateWord);
            translateWord = new TranslateWord();
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.fr, "le beau-père");
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.en, "the step father");
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.es, "el padrastro");
            vocabulary.addTranslateWord(translateWord);
            translateWord = new TranslateWord();
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.fr, "le cousin");
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.en, "the cousin (male)");
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.es, "el primo (hombre)");
            vocabulary.addTranslateWord(translateWord);
            translateWord = new TranslateWord();
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.fr, "le beau-frère");
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.en, "brother in-law");
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.es, "cuñado");
            vocabulary.addTranslateWord(translateWord);
            translateWord = new TranslateWord();
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.fr, "le beau-père");
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.en, "father in-law");
            translateWord.addTranslation(WelcomeScreen.LANGUAGE.es, "suegro");
            vocabulary.addTranslateWord(translateWord);
        } catch (Exception e) {

        }
        vocabularies.add(vocabulary);
    }
}
